import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { Fragment, useEffect, useState } from "react";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import {
  Button,
  CardActionArea,
  CardActions,
  Container,
  Stack,
} from "@mui/material";
import { Box, fontSize } from "@mui/system";

interface DataCard {
  id: number;
  name?: string;
  title: string;
  url: string;
  heading: string;
  ratting: number;
  numberEmission: number;
  isKilogram: boolean;
}

type DataCardsArray = DataCard[];

const Home: NextPage = () => {
  const [data, setData] = useState<DataCardsArray>([]);
  const [fetchError, setFetchError] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    fetch("/api/data")
      .then((res) => {
        if (!res.ok) {
          throw Error("Could not fetch data");
        }
        return res.json();
      })
      .then((data) => {
        setData(data);
      })
      .catch((err) => {
        console.log("error", err);
        setFetchError(true);
      })
      .finally(() => {
        setIsLoading(false);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Task Chooose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ mt: 10 }}>
        <Stack
          direction={{ xs: "column", sm: "row" }}
          spacing={{ xs: 1, sm: 2, md: 4 }}
        >
          {data.map((card) => {
            return (
              <>
                <Card
                  sx={{
                    width: 345,
                    border: "1px solid red",
                    padding: 1,
                    borderRadius: 2,
                  }}
                >
                  <CardActionArea
                    sx={{
                      border: "1px solid blue",
                      borderRadius: 2,
                      backgroundImage: `url(${card.url})`,
                      backgroundSize: "cover",
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      width: "100%",
                      height: "100%",
                      
                    }}
                  >
                    <Box
                      component="div"
                      sx={{
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(0,0,255,0.2)",
                        p:3
                      }}
                    >
                      <CardContent sx={{ p: 2 }}>
                        <Box sx={{ pl: 2, pr: 2 }}>
                          <Typography
                            gutterBottom
                            component="h3"
                            sx={{
                              fontSize: 24,
                              fontWeight: "bold",
                              textAlign: "center",
                              color: "white",
                            }}
                          >
                            {card.title}
                          </Typography>
                          <Typography
                            variant="body2"
                            color="text.secondary"
                            component="p"
                            sx={{
                              fontSize: 16,
                              color: "white",
                              textAlign: "center",
                            }}
                          >
                            {card.heading}
                          </Typography>
                        </Box>
                        <Box
                          sx={{
                            p: 1,
                            mt: 1,
                            mb: 1,
                            backgroundColor: "#333",
                            borderRadius: "16px",
                            display: "flex",
                            justifyContent: "space-around",
                            alignItems: "center",
                          }}
                          component="div"
                        >
                          <Typography
                            gutterBottom
                            component="h3"
                            sx={{
                              fontSize: 16,
                              fontWeight: "bold",
                              textAlign: "center",
                              color: "white",
                              m: 0,
                            }}
                          >
                            {card.title}
                          </Typography>
                          {card.isKilogram ? (
                            <Typography
                              gutterBottom
                              component="h3"
                              sx={{
                                fontSize: 16,
                                fontWeight: "bold",
                                textAlign: "center",
                                color: "white",
                                m: 0,
                              }}
                            >
                              {card.numberEmission}kg CO2
                            </Typography>
                          ) : (
                            <Typography
                              gutterBottom
                              component="h3"
                              sx={{
                                fontSize: 16,
                                fontWeight: "bold",
                                textAlign: "center",
                                color: "white",
                                m: 0,
                              }}
                            >
                              {card.numberEmission}t CO2
                            </Typography>
                          )}
                        </Box>
                      </CardContent>
                    </Box>
                  </CardActionArea>
                  <CardActions></CardActions>
                </Card>
              </>
            );
          })}
        </Stack>
      </Container>
    </div>
  );
};

export default Home;
