import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Container, Stack, Typography } from "@mui/material";
import CardProfile from "../components/CardProfile/CardProfile";

interface DataCard {
  id: number;
  title: string;
  url: string;
  heading: string;
  ratting: number;
  numberEmission: number;
  isKilogram: boolean;
  countriesAmount: number;
  days: number;
}

type DataCardsArray = DataCard[];

const Home: NextPage = () => {
  const [data, setData] = useState<DataCardsArray>([]);
  const [fetchError, setFetchError] = useState(false);

  useEffect(() => {
    const getData = () => {
      fetch("/api/data")
        .then((res) => {
          if (!res.ok) {
            throw Error("Could not fetch data");
          }
          return res.json();
        })
        .then((data) => {
          setData(data);
        })
        .catch((err) => {
          console.log("error", err);
          setFetchError(true);
        });
    };
    getData();

    setInterval(() => {
      getData();
    }, 5000);
  }, []);

  return (
    <div>
      <Head>
        <title>
          Practice: React, Next.js, working with REST API, MUI, working with
          data{" "}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {fetchError ? (
        <>
          <Typography
            gutterBottom
            component="h3"
            sx={{
              fontSize: 15,
              fontWeight: "bold",
              textAlign: "center",
              color: "#000000eb",
              m: 0,
            }}
          >
            Sorry, we could not fetch data. Try again later
          </Typography>
        </>
      ) : (
        <Container sx={{ mt: 10, mx: "auto", mb: "10" }}>
          <Stack
            direction={{ xs: "column", sm: "row" }}
            sx={{
              display: "flex",
              gap: 2,
              flexWrap: "wrap",
              justifyContent: "center",
              alignItems: {
                xs: "center",
              },
            }}
          >
            {data.map((card) => {
              return <CardProfile card={card} key={`card-${card.id}`} />;
            })}
          </Stack>
        </Container>
      )}
    </div>
  );
};

export default Home;
